apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-web #nom 
  namespace: production # tout faire dans le namespace prodution
spec:
  type: NodePort #type de service
  selector:
    app: web #type d'app
  ports:
    - port: 8080 #port expose en interne dans le cluster
      targetPort: 8080 # le port sur lequel les containers ecoutent
      nodePort: 30008 # port d'acces 
